image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - npm install
    - npm run lint

test:
  stage: test
  script:
    - npm install
    - npm run test

deploy_graphcool_staging:
  stage: deploy
  script:
    - 'echo "platformToken: >-\n\t$GC_AUTH_TOKEN" > /builds/etherstellar/functions/.graphcoolrc'
    - npm run gc -- deploy --target dev
  environment:
    name: staging/$CI_COMMIT_REF_SLUG
    url: https://console.graph.cool/EtherstellarDev
  when: manual

deploy_graphcool:
  stage: deploy
  script:
    - 'echo "platformToken: >-\n\t$GC_AUTH_TOKEN" > /builds/etherstellar/functions/.graphcoolrc'
    - npm run gc -- deploy --target prod
  environment:
    name: production
    url: https://console.graph.cool/EtherstellarProd
  when: manual
  only:
    - master
